<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KOLTC207327524" name="Test" tests="3" failures="1" timestamp="9 Aug 2020 15:29:57 GMT" time="13.054" errors="0">
  <testcase name="VerifyLogin" time="0.999" classname="TestCase.TestNG">
    <failure type="java.lang.AssertionError" message="expected [http://13.126.125.146:3001/Login] but found [http://13.126.125.146:3001/]">
      <![CDATA[java.lang.AssertionError: expected [http://13.126.125.146:3001/Login] but found [http://13.126.125.146:3001/]
	at TestCase.TestNG.VerifyLogin(TestNG.java:47)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogin -->
  <testcase name="VerifyTitle" time="0.009" classname="TestCase.TestNG"/>
  <testcase name="VerifyURL" time="0.009" classname="TestCase.TestNG"/>
</testsuite> <!-- Test -->
